### ISSUE TITLE
Add a 'restart' command for restarting bots via IRC

### ISSUE THREAD

**Issue by GLolol** [ProgVal/Limnoria#1070]
Often times this is more convenient than having to log in to the terminal where the bot is running and restart it manually.

**Comment by weedy** [comment]
while :; do ./bot --config; sleep 3; done

**Comment by ProgVal** [comment]
Closing the issue, because @GLolol has wrote a plugin to do that: https://github.com/GLolol/SupyPlugins/tree/master/Restart

Also, using [the systemd unit](https://limnoria.readthedocs.io/en/latest/use/supybot-botchk.html#systemd-service) or [supybot-botchk](https://limnoria.readthedocs.io/en/latest/use/supybot-botchk.html#id1) (which I now consider the preferred ways to run Limnoria) makes it so that `@quit` actually restarts the bot.
