### ISSUE TITLE
String re fails in Python 2 with the g flag, only in running bot (passes tests)

### ISSUE THREAD

**Issue by NP-Hardass** [ProgVal/Limnoria#1072]
Tested with three bots, Py2.7 (thanks @Mikaela), different distros, up to date dependencies.  Any `re m/foo/g` or `re s/foo/bar/g` fails when the bot processes the command during runtime.  This does not apply to the i flag.

Mysteriously, this passes the unit test, but fails at runtime with a message like:
`Error: u'm/foo/g foo' is not a valid regular expression.`

**Comment by GLolol** [comment]
Replacing works fine for me; it's just matching that's broken:

```
<@GLolol> `re s/foo/bar/g foobar
<@Lily> barbar
<@GLolol> `re m/foo/g foobar
<@Lily> Error: 'm/foo/g foobar' is not a valid regular expression.
```

**Comment by NP-Hardass** [comment]
I ran your test case, and for substitution, and that worked.  Then I replaced tweaked it to match what I had been running,  `re "s/foo/bar/g" foobar` and that failed.  This would seem to indicate that at least for the substitution case, how the string is being passed/stored is the source of the issue.

**Comment by GLolol** [comment]
I don't understand.

```
<@GLolol> `re "s/foo/bar/g" foobar
<@Lily> barbar
```

**Comment by jamessan** [comment]
`s///` has special handling to recognize the `g` flag since that isn't a standard Python flag, and it's more relevant for performing replacements.

`m//` doesn't have any support for the `g` flag.  It's currently just used as a proxy for `re.search` and returns the first resulting match.  The reason you're getting the `is not a valid regular expression` is because the `g` flag isn't recognized, so the parser keeps reading the rest of the text and reaches the end without finding a valid regex.

The actual error is `Invalid flag: G`, but that gets swallowed by the parser and there's not really an easy way to bubble that up to the user.

Assuming `g` could be supported for `m//`, what would you want that to look like?
