### ISSUE TITLE
RSS displaying wrong headline at initialAnnounce (??)

### ISSUE THREAD

**Issue by iyx** [ProgVal/Limnoria#1139]
I'm not sure if this is exactly right.

When I add any feed, its initial announce will not be the latest (newest).

But when  I call it by a feed name (trigger), it will correctly show latest headline in the feed.

I don't know if it is trying to display headlines in different order (from oldest to newest) with initialAnnounce or there is some other problem with reading timestamps in the feed.

However I believe this is wrong behavior and initial announce should be the same as if you called it manually.

As I said it is the same for any feed, for example http://rss.slashdot.org/Slashdot/slashdotMain

**Comment by ProgVal** [comment]
Feeds are sorted according to `supybot.plugins.RSS.sortFeedItems`, which defaults to `asInFeed`.
Does it match the behavior you observe?

**Comment by iyx** [comment]
I have set `initialAnnounceHeadlines` to 1 and tested all three options (`asInFeed`, `newestFirst`, `oldestFirst`) with the slashdot feed.

In all cases initial announce was the same, for some reason, and it was always the oldest headline.

**Comment by ProgVal** [comment]
The issue was caused by Slashdot not providing a “published” field to their feed items, so I added a fallback to using the “updated” one.

By the way, while debugging, I noticed another issue in the sort: it was using alphabetical sort on the formatted date, starting with the name of the weekday… So, thanks a lot
