### ISSUE TITLE
Make the user-agent for HTTP requests configurable

### ISSUE THREAD

**Issue by ProgVal** [ProgVal/Limnoria#1382]
May be useful to access websites with rules blocking the default user-agent.

**Comment by oddluck** [comment]
I could tackle this one, do you want to just use one user-agent or randomly select from a list like SpiffyTitles?

**Comment by koobs** [comment]
@oddluck Thanks for offering to pick this up Gordan! :)

From our use of Limnoria for #freebsd* channel management on freenode IRC, i can summarize our needs with respect to User-Agent as follows:

 1. Set a default and global User-Agent value that applies to all outbound requests

This allows all requests to have a safe/unique default. We use this so our Plugins that use *.freebsd.org services can uniquely identify themselves, to ascertain IRC service usage numbers.

 1. Set or override User-Agent value on a per-plugin basis 

This allows a plugin to set a target specific user-agent. Example: A TweetPlugin can set User-Agent: X needed only for interacting with the Twitter API.

 1. Set or override User-Agent on an individual request or plugin method/class basis

This allows a plugin with multiple target/destinations to set class specific user-agent value. Example: a NewsPlugin with multiple news distinct sources that might require custom User-Agent values specific to it

**Comment by oddluck** [comment]
@koobs have you looked at [SpiffyTitles](https://github.com/oddluck/limnoria-plugins/tree/master/SpiffyTitles)? It already handles user agents per-channel as well as offering different handlers for Twitter links etc. and is better equipped to handle such changes than limnoria core. I was just looking to close this issue not rewrite the web plugin when SpiffyTitles already covers the same ground and is a recommended plugin at https://limnoria.net/plugins.xhtml

**Comment by koobs** [comment]
@oddluck Thanks for the prompt response Gordon, and yep we're aware of spiffytitles :)

The originating motivation that prompted @ProgVal to kindly created this issue was for requests that Limnoria can make for plugins not related to title snarfing.

This feels very much in 'core framework' territory, and I would expect that SpiffyTitles (and other plugins) [1] would/could use that core framework mechanism for its requests once landed.

[1] https://github.com/oddluck/limnoria-plugins/search?q=user-agent&unscoped_q=user-agent
[2] https://github.com/oddluck/limnoria-plugins/blob/master/SpiffyTitles/plugin.py

**Comment by koobs** [comment]
One might start or increment our way there by having a / moving the get_user_agent() method to core, where if its a single entry, its static (configurable), and if it contains multiple entries a random one is returned. 

We can then look to extent that 'global' request method functionality to allow plugin overrides per plugin, class as extensions

**Comment by oddluck** [comment]
@koobs I understand, recent versions of SpiffyTitles are using the url snarfing regex in utils.web so I'm not opposed to calling on core functions. Also agree that the user agent selection should be a one or random selection, which is why I inquired about it earlier (changes like this are in my wheelhouse). Just pointing out that even if I add a configurable user-agent it will require plugin devs using utils.web to take advantage of it, and that per-url overrides will need to be handled on a per-plugin basis.

**Comment by oddluck** [comment]
So this has been committed... However, there's a potential issue with the Google plugin as a result. Using the protocols.userAgents config to specify a modern browser will cause google to serve up more JavaScript, thus breaking the html parser of the google plugin... DDG doesn't use utils.web.defaultHeaders so no issue there. Currently only the Google and Web plugins take advantage of this config setting and Web is not adversely affected by the change.
