### ISSUE TITLE
Inelevant handling of file/filesystem exceptions

### ISSUE THREAD

**Issue by danshearer** [progval/Limnoria#1513]
As documented in this issue in the [Limnoria plugin Hcoop-meetbot](https://github.com/pronovic/hcoop-meetbot/issues/28#issuecomment-1192614030) there is a class of common error that is (a) not caught and (b) not passed up the stack. I don't know what the architecturally best solution is, but it seems worth considering if this is desirable.

I should point out that in the case I have documented, there was complete error recovery, and "out of space" was clearly indicated in the exception. I can imagine that other problems in this class, such as obscure or transient file permission problems would not be so easy to diagnose.

Thanks for Limnoria.

**Comment by progval** [comment]
I don't understand what the issue is, as the error is logged as expected. What else could Limnoria do?

If you want logs sent to a channel (instead of just the filesystem and syslog), you can use the LogToIrc plugin.

**Comment by progval** [comment]
> I typed #endmeeting, and nothing happened. And once more, still nothing happened.

I don't see how this is related to the error you pasted, as your paste only contains log from the background database dumps, which are not necessary for normal operations.

I see that hcoop-meetbot has its own database system, so I feel that your problem should actually be handled in hcoop-meetbot's code; but they did not realize because you sent them logs of the wrong issue.
